data_promoter: "data/breast_vert_promoter.csv"
data_provider: "data/breast_vert_provider.csv"
promoter_data_table: "breast_mix_promoter0"
provider_data_table: "breast_mix_provider0"
idx: "id"
label_name: "y"
