data_promoter: "data/breast_horz_promoter.csv"
data_provider: "data/breast_horz_provider.csv"
#data_test: "data/breast_horz_test.csv"
idx: "id"
label_name: "y"
data_promoter_train: "breast_horz_promoter"
data_promoter_val: "breast_horz_promoter"
data_provider_train: "breast_horz_provider"
data_provider_val: "breast_horz_provider"
eval_type: "binary"
task_type: "classification"
loss_func: "cross_entropy"
tree_depth: 5
tree_num: 10
learning_rate: 0.1
